// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  discord: __t.string(),
  riotIdGameName: __t.string().name("riot_id_game_name"),
  riotIdTagline: __t.string().name("riot_id_tagline"),
  currentRank: __t.string().name("current_rank"),
  peakRank: __t.string().name("peak_rank"),
  mainRole: __t.string().name("main_role"),
  secondaryRole: __t.option(__t.string()).name("secondary_role"),
});
