// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  id: __t.u32(),
  name: __t.string(),
  discord: __t.string(),
  riotIdGameName: __t.string(),
  riotIdTagline: __t.string(),
  currentRank: __t.string(),
  peakRank: __t.string(),
  mainRole: __t.string(),
  secondaryRole: __t.option(__t.string()),
});
export type Player = __Infer<typeof Player>;

